### ISSUE TITLE
Make the theme qBittorrent v5 compatible

### ISSUE THREAD

**Issue by JohanSF** [CallMeBruce/nightwalker#4]
As binhex writes here: https://github.com/repslet/nightwalker/issues/20#issue-2631251659

Quote:

> Hi love this theme, any chance you can fix up the theme to support qBittorrent v5 please.
> 
> Things I have noticed so far (there could and probably are more):
> 
> - missing paused/stopped icon
> - Inability to pause any torrents

It looks like this fork might have fixed these issues: https://github.com/Jorsher/nightwalker

**Comment by joshft91** [comment]
@Jorsher, if your code is ready, would you be willing to put your fork up for review against CallMeBruce's repo? May be able to get this merged in to get it working for hotio images.

**Comment by Jorsher** [comment]
> @Jorsher, if your code is ready, would you be willing to put your fork up for review against CallMeBruce's repo? May be able to get this merged in to get it working for hotio images.

To be honest, I don't know how to do that and I'm not sure my changes are up to snuff.

Essentially I just find/replace-d all variants of pause/paused/resume/resumed with stop/stopped/start/started. May have even changed some that didn't need to be changed. Because of this, it won't work with versions prior to 5.0. Pause icon should probably be changed to a Stop one too :)

Qbit dark theme wasn't quite as sleek as this and it was the main thing holding me back from upgrading to 5.0.

**Comment by rakosi2** [comment]
You can create a pull request in the pull request tab. However, you don't want to add the changes to the README so the easiest way is to make a new branch and checkout the main commit or cherry-pick it and pull request that branch.
Don't worry about incompatibility for older Qbit as @CallMeBruce could make a new branch for pre-5.0 or people can checkout the version that they want.

**Comment by IIIdefconIII** [comment]
Unacceptable file type, only regular file is allowed.

**Comment by CallMeBruce** [comment]
Just did a re-combine of latest 5.0.2 version and the nightwalker theme. Let me know if you find something that isn't working.
